apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-custom-rules
  namespace: monitoring
  labels:
    role: prometheus-rulefiles
data:
  custom-rules.yaml: |
    groups:
      - name: example.rules
        rules:
          - alert: PodFailure
            expr: kube_pod_status_phase{phase="Failed"} > 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Pod failed to start"
              description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has failed to start."

          - alert: WebsiteDown
            expr: probe_success{job="blackbox"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Public website is down"
              description: "The public website is down."
